version: "3.8"

services:
  database:
    image: mariadb:latest
    container_name: todo_db
    environment:
      - MYSQL_ROOT_PASSWORD=DB1234
      - MYSQL_DATABASE=todoapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=DB1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: todo_db
      DB_USER: root
      DB_PASSWORD: DB1234
      DB_DATABASE: todoapp
      DB_PORT: 3306
      PORT: 5000
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: